baseURL = "https://spidy25ug-apu.github.io/hello-world/"
title = "My New Hugo Project"
theme = "ananke"
publishDir = "public"

defaultContentLanguage = "en"

[params]
  author = "Piyush"
  description = "My Hugo Blog"